// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAhvJoa0kXLkLdcXCgrUIRNu4_8-60Nk0',
    appId: '1:298886773949:web:d7f0c5a6bb9723e4430bd4',
    messagingSenderId: '298886773949',
    projectId: 'appdevmyproject',
    authDomain: 'appdevmyproject.firebaseapp.com',
    storageBucket: 'appdevmyproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAregRzSk-_ItPJrMUUkHDPgZMamxAtN1A',
    appId: '1:298886773949:android:7fad2bcd3ca684c9430bd4',
    messagingSenderId: '298886773949',
    projectId: 'appdevmyproject',
    storageBucket: 'appdevmyproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOugBZc1Ge-FfyE7FVqFxIAyepo4jSI9g',
    appId: '1:298886773949:ios:517d0b6c227a11db430bd4',
    messagingSenderId: '298886773949',
    projectId: 'appdevmyproject',
    storageBucket: 'appdevmyproject.appspot.com',
    iosClientId: '298886773949-j9shrdhjtl8p343sq672q40uboc74n37.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOugBZc1Ge-FfyE7FVqFxIAyepo4jSI9g',
    appId: '1:298886773949:ios:1916b3c55ed3a1fa430bd4',
    messagingSenderId: '298886773949',
    projectId: 'appdevmyproject',
    storageBucket: 'appdevmyproject.appspot.com',
    iosClientId: '298886773949-peh0v9uiht22qh4t5g3891osl94ouslt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject.RunnerTests',
  );
}
